### ISSUE TITLE
Not all map polylines are displayed

### ISSUE THREAD

**Issue by freaklow** [fsiamp/mapnacket#1]
When multiple map spots are inserted by right-clicking and then these ones exceed a specific limit then during submission of POST, the new pins/coordinates are not displayed.

So no polylines are appeared too inside the map.

The differences on how map spots are displayed before and after POST request can be found in the attached files.

![before](https://cloud.githubusercontent.com/assets/5954411/18606480/46c7643c-7cba-11e6-8f33-2144c6b440c0.png)

![after](https://cloud.githubusercontent.com/assets/5954411/18606482/50258ee6-7cba-11e6-9bfc-115f37711969.png)

**Comment by fsiamp** [comment]
Correction is needed in mapnacket_api.php which is responsible for handling every possible coordinate pair (latitude,longitude).

The first option would be to retrieve coordinates dynamically and based on the total number of points then a relevant mapview to be displayed. An alternative and easier solution would be just to add more conditions in mapnacket_api.php in order to be able to handle more spots.

**Comment by fsiamp** [comment]
Fix was committed by increasing the limit of possible map routes. Now more map polylines would be able to be displayed in canvas (max 20) .
